using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace DistSysAcwServer.Models
{
    /// <summary>
    /// Represents a log entry recording a user's API interaction.
    /// Each log is associated with a User via the UserApiKey foreign key.
    /// </summary>
    public class Log
    {
        /// <summary>
        /// Unique primary key for the log entry. Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LogId { get; set; }

        /// <summary>
        /// Describes what action was performed (e.g. "User requested /Protected/Hello").
        /// </summary>
        public required string LogString { get; set; }

        /// <summary>
        /// The date and time at which the log entry was created.
        /// </summary>
        public DateTime LogDateTime { get; set; }

        /// <summary>
        /// Foreign key linking this log to the user who performed the action.
        /// Nullable so that logs survive user deletion (set to null on delete).
        /// </summary>
        public string? UserApiKey { get; set; }

        /// <summary>
        /// Navigation property to the associated user.
        /// </summary>
        [ForeignKey("UserApiKey")]
        public virtual User? User { get; set; }

        /// <summary>
        /// Parameterless constructor required by Entity Framework.
        /// </summary>
        public Log() { }

        /// <summary>
        /// Convenience constructor that creates a log entry with the current timestamp.
        /// </summary>
        /// <param name="logString">Description of the action performed.</param>
        [SetsRequiredMembers]
        public Log(string logString)
        {
            LogString = logString;
            LogDateTime = DateTime.Now;
        }
    }
}