using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DistSysAcwServer.Models
{
    /// <summary>
    /// Archived log entry preserved after a user is deleted.
    /// Retains the original UserApiKey for audit purposes even though
    /// the corresponding User record no longer exists.
    /// </summary>
    public class LogArchive
    {
        /// <summary>
        /// Unique primary key for the archived log entry. Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LogArchiveId { get; set; }

        /// <summary>
        /// Describes what action was performed.
        /// </summary>
        public string LogString { get; set; }

        /// <summary>
        /// The date and time at which the original log entry was created.
        /// </summary>
        public DateTime LogDateTime { get; set; }

        /// <summary>
        /// The API Key of the user who performed the action.
        /// Stored as a plain string — no foreign key constraint, since the user has been deleted.
        /// </summary>
        public string UserApiKey { get; set; }

        /// <summary>
        /// Parameterless constructor required by Entity Framework.
        /// </summary>
        public LogArchive() { }
    }
}